apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-service
data:
  USER_SERVICE_URL: "http://user-service.user-service.svc.cluster.local"
  PRODUCT_SERVICE_URL: "http://product-service.product-service.svc.cluster.local"
  DB_URL: "jdbc:postgresql://host.docker.internal:5434/orderdb"
  DDL_AUTO: "validate"
  LOG_LEVEL: "INFO"
  JAVA_OPTS: "-Xmx512m -Xms256m"
