# ============================================
# CONFIGMAP - Configuración NO sensible
# ============================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: payment-service
  labels:
    app: payment-service

# Pares clave-valor
data:
  # URL de la base de datos
  DB_URL: "jdbc:postgresql://host.docker.internal:5435/paymentdb"

  # Kafka
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:9092"

  # Configuración de JPA
  DDL_AUTO: "validate"
  SHOW_SQL: "false"

  # Pool de conexiones
  POOL_SIZE: "10"

  # Logging
  LOG_LEVEL: "INFO"
  SQL_LOG_LEVEL: "WARN"

  # JVM
  JAVA_OPTS: "-Xmx512m -Xms256m"
