apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: notification-service
data:
  DB_URL: "jdbc:postgresql://host.docker.internal:5437/notificationdb"
  DDL_AUTO: "validate"
  LOG_LEVEL: "INFO"
