apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-service-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-service-secret
                  key: DB_PASSWORD
