apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: delivery-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: delivery-service-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: delivery-service-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: delivery-service-secret
                  key: DB_PASSWORD
